name: CI - PR

on:
  workflow_call:
  workflow_dispatch:
  push:
    tags:
      - '**'
  pull_request:

jobs:
  reject-trailing-whitespace:
    uses: ./.github/workflows/trailing-whitespace.yaml

  cargo-shear:
    name: Cargo Shear
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Run cargo-shear
        uses: ./.github/actions/cargo-shear

  cargo-checkmate:
    uses: ./.github/workflows/cargo-checkmate.yaml

  cargo-hack-check:
    name: Cargo Hack Check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Run cargo-hack
        uses: ./.github/actions/cargo-hack
        with:
          hack-subcommand: check
  test:
    uses: ./.github/workflows/test.yaml
